### ISSUE TITLE
Port to ROS2

### ISSUE THREAD

**Issue by wuehr1999** [107-systems/l3xz_mapping#7]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### ⚡ Feature Request

Port this node to ROS2 galactic using the corresponding version of rtabmap.

**Comment by aentinger** [comment]
Ping @wuehr1999 .

When looking through the code bases I noticed that this package has not been ported to ROS2 yet (or so it seems).

May I ask what's the current state?

**Comment by wuehr1999** [comment]
Hi @aentinger, I am not sure if the mapping from known position will stay in this repository, as it is not really a usecase for reconning. The porting of the rtabmap solution is currently under test and will be committed during the next weeks.

**Comment by aentinger** [comment]
Allright. I think I miss of a bit of insight what's actually integrated with this repository. We'll talk it over at our next in-person meeting :wink: .
